name: Typeset article
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  typeset-paper:
    name: Typeset article
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Typeset article
        run: latexmk -pdf -Werror tb139starynovotny-testing.ltx
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tb139starynovotny-testing
          path: tb139starynovotny-testing.pdf
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: tb139starynovotny-testing.pdf
